[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --partition-table partitions.csv"

[env]
ESP_LOG="info"

[build]
target = "xtensa-esp32s3-none-elf"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core"]
